name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '04 01 * * *'

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/quote-readme@main
        with:
          COMMIT_MESSAGE: 🍵 Had some interesting thoughts about life. Coulnd''t wait to update it!      # default - Update with quote-readme
          OPTION: funfact           # default - both, can be one of (quote, funfact, both), if 'both' then will display either a quote or a fact
